version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_password
      POSTGRES_DB: portfolio_db
    volumes:
      # связываем физический диск /mnt/db_data с внутренней папкой БД
      - /mnt/db_data:/var/lib/postgresql/data

  web:
    build: ./app
    restart: always
    ports:
      - "5000:5000"
    environment:
      # Передаем нашему Flask-коду доступы от БД
      DATABASE_URL: postgresql://devops_user:devops_password@db:5432/portfolio_db
    depends_on:
      - db
