services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_password
      POSTGRES_DB: portfolio_db
    volumes:
      - /mnt/db_data:/var/lib/postgresql/data
    # НОВОЕ: Учим Докер проверять, готова ли база принимать запросы
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devops_user -d portfolio_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./app
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://devops_user:devops_password@db:5432/portfolio_db
    depends_on:
      # НОВОЕ: Ждем не просто старта контейнера, а именно статуса "здоров"
      db:
        condition: service_healthy
