events {}

stream {
    server {
        listen 5432;
        
        # 'postgres_db' - это имя нашего сервиса в docker-compose.yml
        # Внутренний DNS докера сам найдет его IP адрес!
        proxy_pass postgres_db:5432;
    }
}
