apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  namespace: skate-dev
spec:
  selector:
    app: skateboard-api  # Важно: должно совпадать с label в Поде!
  ports:
    - protocol: TCP
      port: 80           # Порт, который слушает Сервис
      targetPort: 8080   # Порт, на котором реально работает приложение в контейнере
  type: ClusterIP
