[docker_targets]
172.17.0.3 ansible_user=root ansible_password=root
172.17.0.4 ansible_user=root ansible_password=root

[docker_targets:vars]
# Отключаем проверку ключей, так как это тестовые контейнеры
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
