name: Ansible Infra Deployment

on:
  push:
    branches: [ "main" ]
  paths:
     - 'ansible-project/**' 
     - '.github/workflows/deploy_myservers_docker.yml'
     - 'docker-compose.yml'

jobs:
  run-ansible:
    runs-on: self-hosted

    steps:
      - name: Загрузка актуального кода (Checkout)
        uses: actions/checkout@v4

      - name: Настройка временного SSH ключа
        run: |
          mkdir -p ~/.ssh
          # Достаем ключ из секретов и кладем во временный файл
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          # Обязательно урезаем права, иначе SSH откажется его использовать
          chmod 600 ~/.ssh/deploy_key

      - name: Запуск Ansible Playbook
        env:
          # Важно для автоматики! Отключаем проверку "Are you sure you want to continue connecting?"
          ANSIBLE_HOST_KEY_CHECKING: False 
        run: |
          cd ansible-project
          ansible-playbook -i hosts.ini install-docker.yml --private-key ~/.ssh/deploy_key
      - name: Запуск Ansible Playbook (Деплой Приложения)
        env:
          ANSIBLE_HOST_KEY_CHECKING: False 
        run: |
          cd ansible-project
          ansible-playbook -i hosts.ini deploy-app.yml --private-key ~/.ssh/deploy_key
