[webservers]
127.0.0.1 ansible_connection=local
130.49.174.52 ansible_user=root # VDS2
158.160.118.80 ansible_user=aleks # Yandex.cloud

[prod_server]
158.160.118.80 ansible_user=aleks # Yandex.cloud
